name: Publish Release

on:
  release:
    types:
      - published

jobs:
  build-pypi:
    name: Build PyPi 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ITProKyle/action-setup-python@v1.0.0
        with:
          poetry-install: false
          poetry-plugins: poetry-dynamic-versioning
      - name: Run Build
        run: make build
      - name: Upload Distribution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist
  publish-pypi:
    name: Publish 📦 To PyPI
    needs:
      - build-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - uses: ITProKyle/action-setup-python@v1.0.0
        with:
          poetry-install: false
          poetry-plugins: poetry-dynamic-versioning
      - name: Publish Distribution 📦 to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_password }}
        run: poetry publish
